<style type="text/css"> 
<!--
input        { border-style: solid; border-width: 1px }



body { 
	 COLOR: grey;
	 font-family: Tahoma, Verdana, Geneva, Arial, Helvetica, sans-serif;
	 }


p {
  font-family: tahoma, verdana, arial, helvetica, sans-serif; 
  line-height: 12pt;
  margin: 0 0 10px 0;
  padding: 0;
}


a {
  COLOR: darkblue;
  TEXT-DECORATION: none;

  FONT-VARIANT: small-caps;
}

a:hover {
  color: red;
  text-decoration: none;
}


-->
</style>